name: PlayerTimeWeather
author: J Cliff Armstrong (A.K.A. JadedDragoon)
main: net.scrapironcity.ptw.ptw
version: 0.2.1
api-version: 1.15
commands:
   ptw:
      description: View your current Player Time & Weather status
      usage: /ptw
   ptw status:
      description: View your current Player Time & Weather status
      usage: /ptw status
   ptw tset:
      description: Set your personal (apparent) time
      usage: /ptw tset <time>
   ptw rtset:
      description: Set your relative personal (apparent) time
      usage: /ptw rtset <time-offset>
   ptw tsync:
      description: Syncronize your personal (apparent) time with the server (actual) time.
      usage: /ptw tsync
   ptw wset:
      description: Set your personal (apparent) weather
      usage: /ptw tset <CLEAR|DOWNFALL>
   ptw wsync:
      description: Syncronize your personal (apparent) weather with the server (actual) weather.
      usage: /ptw tsync